# Generated by Django 5.2.1 on 2025-05-19 19:47

from django.db import migrations


def populate_data(apps, schema_editor):
    Album = apps.get_model('music_albums', 'Album')
    Review = apps.get_model('music_albums', 'Review')

    # Album 1
    album1 = Album.objects.create(title='The Dark Side of the Moon', artist='Pink Floyd', release_year=1973, genre='Progressive Rock')
    Review.objects.create(album=album1, reviewer_name='MusicFan123', comment='A timeless classic!', rating=5)
    Review.objects.create(album=album1, reviewer_name='AudiophileAl', comment='Incredible soundscapes.', rating=5)

    # Album 2
    album2 = Album.objects.create(title='Thriller', artist='Michael Jackson', release_year=1982, genre='Pop')
    Review.objects.create(album=album2, reviewer_name='PopPrincess', comment='King of Pop for a reason!', rating=5)
    Review.objects.create(album=album2, reviewer_name='80sKid', comment='Still makes me want to dance.', rating=4)

    # Album 3
    album3 = Album.objects.create(title='Abbey Road', artist='The Beatles', release_year=1969, genre='Rock')
    Review.objects.create(album=album3, reviewer_name='BeatlesFanatic', comment='Pure genius from start to finish.', rating=5)
    Review.objects.create(album=album3, reviewer_name='GuitarHero', comment='Iconic riffs and melodies.', rating=5)


class Migration(migrations.Migration):

    dependencies = [
        ('music_albums', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
