# Generated by Django 5.2.1 on 2025-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_albums', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
